server:
  port: 9002

spring:
  application:
    name: USER-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/  #this is the url of service registry where this webservice will register itself
  instance:
    hostname: localhost
